# Generated by Django 5.2.8 on 2026-05-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_gender_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_services',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.gender'),
        ),
        migrations.AlterField(
            model_name='child_services',
            name='main_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_services', to='services.mainservices'),
        ),
        migrations.AlterField(
            model_name='mainservices',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_services', to='services.gender'),
        ),
    ]
